"""remove weekly_fast_goal

Revision ID: b280894ed6c7
Revises: 
Create Date: 2026-02-20 03:46:17.837411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b280894ed6c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('weekly_fast_goal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weekly_fast_goal', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
